# Generated by Django 5.0.13 on 2026-07-21 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional_location', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('voltage', models.CharField(blank=True, max_length=16)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=32, unique=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='line',
            name='sap_line_id',
        ),
        migrations.AddField(
            model_name='employeecadresnapshot',
            name='reporting_manager_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employeecadresnapshot',
            name='reporting_manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inspection',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='employeecadresnapshot',
            index=models.Index(fields=['reporting_manager_id'], name='line_inspec_reporti_ae06d7_idx'),
        ),
        migrations.AddField(
            model_name='line',
            name='sap_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='line_inspection.sapline'),
        ),
    ]
