# Generated by Django 5.0.13 on 2026-07-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_inspection', '0002_sapline_superadmin_remove_line_sap_line_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(blank=True, choices=[('ground_patrol', 'Ground Patrolling'), ('pmi', 'Pre-Monsoon Inspection')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='last_inspection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='last_inspection_type',
            field=models.CharField(blank=True, choices=[('ground_patrol', 'Ground Patrolling'), ('pmi', 'Pre-Monsoon Inspection')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='last_worst_criticality',
            field=models.CharField(choices=[('none', 'Not inspected'), ('ok', 'Normal'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='none', max_length=16),
        ),
        migrations.AddIndex(
            model_name='tower',
            index=models.Index(fields=['last_inspection_at'], name='line_inspec_last_in_964e86_idx'),
        ),
    ]
