# Generated by Django 5.0.13 on 2026-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_inspection', '0003_inspection_inspection_type_tower_last_inspection_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='circuit_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='circuit_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tower',
            name='conductor_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tower',
            name='cp_sp',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tower',
            name='date_of_commissioning',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tower',
            name='insulator_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tower',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tower',
            name='no_of_conductors_per_phase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='relay_setting_length_in_km',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tower',
            name='span_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='structure_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tower',
            name='tower_ckts_conductor',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tower',
            name='type_of_earthing',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='tower',
            index=models.Index(fields=['voltage', 'is_active'], name='line_inspec_voltage_c34fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='tower',
            index=models.Index(fields=['structure_key'], name='line_inspec_structu_5add1c_idx'),
        ),
    ]
