# Generated by Django 5.0.13 on 2026-07-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_inspection', '0004_tower_circuit_count_tower_circuit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='sap_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='line_inspection.sapline', unique=True),
        ),
    ]
