# Generated by Django 5.0.13 on 2026-07-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_inspection', '0005_alter_line_sap_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTowerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=32)),
                ('assigned_by_employee_id', models.CharField(max_length=32)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tower',
            name='line_offset_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='line_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='sap_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line', to='line_inspection.sapline'),
        ),
        migrations.AddIndex(
            model_name='tower',
            index=models.Index(fields=['line', 'line_sequence'], name='line_inspec_line_id_ee6786_idx'),
        ),
        migrations.AddField(
            model_name='linetowerassignment',
            name='from_tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='range_starts', to='line_inspection.tower'),
        ),
        migrations.AddField(
            model_name='linetowerassignment',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_ranges', to='line_inspection.line'),
        ),
        migrations.AddField(
            model_name='linetowerassignment',
            name='to_tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='range_ends', to='line_inspection.tower'),
        ),
        migrations.AddIndex(
            model_name='linetowerassignment',
            index=models.Index(fields=['employee_id', 'is_active'], name='line_inspec_employe_dfc14e_idx'),
        ),
        migrations.AddIndex(
            model_name='linetowerassignment',
            index=models.Index(fields=['line', 'is_active'], name='line_inspec_line_id_3adf08_idx'),
        ),
    ]
