# Generated by Django 5.0.13 on 2026-07-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_inspection', '0006_linetowerassignment_tower_line_offset_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiloEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lilo_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by_employee_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('new_lines', models.ManyToManyField(blank=True, related_name='lilo_events_as_new', to='line_inspection.line')),
                ('old_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lilo_events_as_old', to='line_inspection.line')),
                ('split_tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lilo_split_events', to='line_inspection.tower')),
            ],
        ),
        migrations.CreateModel(
            name='LiloTowerRemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_object_id', models.CharField(blank=True, max_length=64)),
                ('new_object_id', models.CharField(blank=True, max_length=64)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(choices=[('auto', 'Auto (high-confidence match)'), ('manual', 'Manual (operator override)'), ('new', 'New tower (no match)')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remaps', to='line_inspection.liloevent')),
                ('surviving_tower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lilo_remaps', to='line_inspection.tower')),
            ],
        ),
    ]
