# Generated by Django 5.0.13 on 2026-07-23 12:09

import line_inspection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_inspection', '0007_liloevent_lilotowerremap'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='gps_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='gps_distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='presence_flag',
            field=models.CharField(blank=True, choices=[('in_range', 'In range (<=50 m)'), ('out_of_range', 'Out of range (overridden)'), ('no_fix', 'No GPS fix (overridden)')], max_length=16),
        ),
        migrations.CreateModel(
            name='MobileAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('employee_id', models.CharField(db_index=True, max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=line_inspection.models._default_token_expiry, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['employee_id', 'is_active'], name='line_inspec_employe_2e6524_idx')],
            },
        ),
    ]
