"""
Django settings for transcoapps project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    """Load BASE_DIR/.env.local (gitignored, never committed) into
    os.environ, if present. Runs here — the very first thing settings.py
    does — so it applies no matter how the server process gets started
    (integrated terminal, a separate terminal that never sourced anything,
    an IDE's Run/Debug button, a task runner, etc). Dot-sourcing a shell
    script only sets env vars in that one shell session; this doesn't have
    that gap."""
    env_file = BASE_DIR / '.env.local'
    if not env_file.exists():
        return
    for line in env_file.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip())


_load_local_env()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3()c882j9mhb22(e*!=5be=^$jt58g%bk8r18o2hs6d4t!^q8!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts allowed to reach this backend. Includes the reserved ngrok static
# domain (used by the drone_inspection_app over LTE/internet), plus localhost
# and the LAN/hotspot ranges for the office/field HTTP fallback.
ALLOWED_HOSTS = [
    'mammal-calamari-create.ngrok-free.dev',
    '.ngrok-free.dev',
    '.ngrok-free.app',
    'localhost',
    '127.0.0.1',
    '[::1]',
    '192.168.137.1',  # Windows Mobile Hotspot default gateway
]

# Comma-separated extras from the environment, so a developer can add their
# current Wi-Fi IP (needed for a phone on the same network to reach
# `runserver 0.0.0.0:8000`) without editing this file. Set in .env.local.
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('EXTRA_ALLOWED_HOSTS', '').split(',') if h.strip()]

# Trust the ngrok HTTPS origin for CSRF-protected POSTs (admin, session auth).
# The mobile API itself uses DRF, but this keeps the browsable admin working
# through the tunnel too.
CSRF_TRUSTED_ORIGINS = [
    'https://mammal-calamari-create.ngrok-free.dev',
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    # 'contacts',         # not part of this checkout
    # 'image_inventory',  # not part of this checkout
    # 'gisdata',          # not part of this checkout
    'line_inspection',
    # 'vendor',
    # 'scada_data'
    # 'organisation_chart',
]

DATABASE_ROUTERS = ['line_inspection.db_router.LineInspectionRouter']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Memoizes the oversight-scope resolution for the life of each request — see
    # the class docstring. Nothing is held past the response.
    'line_inspection.middleware.ScopeMemoMiddleware',
]

ROOT_URLCONF = 'transcoapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'line_inspection.context_processors.identity',
            ],
        },
    },
]

WSGI_APPLICATION = 'transcoapps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Both connections point at the same PostgreSQL database; they differ only in
# which schema they resolve unqualified table names against. Django's own
# tables (auth/admin/sessions/contenttypes) live in `public` on `default`;
# the line_inspection platform tables live in `clear` and are routed to
# `line_inspection_db` by LineInspectionRouter, which never reads or writes
# any other schema.
#
# Credentials come from the environment so a deployment never has to edit
# this file; the fallbacks are the local development server. Set them in
# BASE_DIR/.env.local (read by _load_local_env() at the top of this file) or
# as real environment variables:
#
#   PG_NAME  PG_USER  PG_PASSWORD  PG_HOST  PG_PORT
#
# The `employee_login_db` and `image_inventory_db` aliases were dropped along
# with the contacts/image_inventory apps that used them — they are not part
# of this checkout.

_POSTGRES = {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': os.environ.get('PG_NAME', 'aptransco_ai_db'),
    'USER': os.environ.get('PG_USER', 'postgres'),
    'PASSWORD': os.environ.get('PG_PASSWORD', 'subhash'),
    'HOST': os.environ.get('PG_HOST', 'localhost'),
    'PORT': os.environ.get('PG_PORT', '5432'),
}

DATABASES = {
    'default': {**_POSTGRES},
    # The alias must stay in sync with line_inspection.db_router.DB_ALIAS.
    'line_inspection_db': {
        **_POSTGRES,
        'OPTIONS': {'options': '-c search_path=clear'},
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'contacts/static/'),
    # os.path.join(BASE_DIR, 'image_inventory/static/'),
    # os.path.join(BASE_DIR, 'gisdata/static/'),
    # os.path.join(BASE_DIR, 'vendor/static/'),
    # os.path.join(BASE_DIR, 'scada_data/static/'),
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


KEYCLOAK_BASE_URL = 'https://keycloak.aptransco.co.in'
KEYCLOAK_REALM = 'APTRANSCO-EMP'
KEYCLOAK_CLIENT_ID = 'clear'
KEYCLOAK_CLIENT_SECRET = 'hUEGqxJTNgXxlGuSsAFy4LePclLGiBAz'


# ---------------------------------------------------------------------------
# Line inspection — who may record an inspection
# ---------------------------------------------------------------------------
# When on (the default), ANY authenticated employee may record an inspection on
# any tower, instead of only the towers an EE granted them via a RoleAssignment.
#
# Open access is a deliberate operational choice. The read scope is already
# wider than the old capture scope — a supervisor sees their whole oversight
# subtree and management sees every subdivision — so in practice this lets
# people inspect what they can already see. It also unblocks the case that made
# the old rule untenable: an employee with no RoleAssignment row could inspect
# nothing at all, because visible_lines() returns an empty queryset for them.
#
# Scope of this flag — it governs RECORDING AN INSPECTION only:
#   * closing a defect ticket keeps its own supervisory scoping (api/views.py)
#   * every read / oversight queryset (viewing.py) is untouched
#   * the GPS proof-of-presence gate is untouched and still applies
#
# Set LINE_INSPECTION_OPEN_INSPECT=0 to restore per-assignment scoping; the
# original logic is intact in jurisdiction.can_edit_tower and still tested.
LINE_INSPECTION_OPEN_INSPECT = os.environ.get('LINE_INSPECTION_OPEN_INSPECT', '1') != '0'
