"""
Django settings for aptransco_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Security-sensitive settings are read from the environment so a production
# deployment never has to edit this file. The fallbacks keep local
# development working with zero setup.
#
#   DJANGO_SECRET_KEY   - REQUIRED in production (any long random string)
#   DJANGO_DEBUG        - set to "false" in production
#   DJANGO_ALLOWED_HOSTS - comma-separated, e.g. "api.example.com,10.0.0.5"

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-h%i+16z(5)6hr92+pmm!sd%plzxnkj7k&1a)=e61g(pz91$=8&',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'true').strip().lower() not in (
    'false', '0', 'no', 'off',
)

_default_hosts = (
    '127.0.0.1,192.168.10.19,10.0.2.2,10.100.109.90,10.100.109.215,'
    'localhost,.ngrok-free.dev,.ngrok-free.app'
)
_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS')
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
elif DEBUG:
    # The dev machine's LAN IP changes every time it joins a new WiFi
    # network, and the phone can't reach the backend until that new IP is
    # whitelisted here. Rather than editing this file every time, accept
    # any host while DEBUG is on — never true for a real deployment, where
    # DJANGO_ALLOWED_HOSTS must be set explicitly (see above).
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [h.strip() for h in _default_hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'inspections',
    'line_inspection',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Compresses JSON responses (history/status payloads shrink ~5-10x) —
    # significant on slow field connections and tunneled (ngrok) links.
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aptransco_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aptransco_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # The APTRANSCO line-inspection platform (towers, catalog, inspections,
    # tickets) lives in an externally-owned PostgreSQL database, in the
    # `clear` schema. The `line_inspection` app maps those tables with
    # managed=False models and is routed here by ClearDbRouter. The legacy
    # `inspections` app and all of Django's own tables stay on `default`
    # (SQLite). Credentials come from the environment with dev fallbacks.
    'clear_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('CLEAR_DB_NAME', 'aptransco_ai_db'),
        'USER': os.environ.get('CLEAR_DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('CLEAR_DB_PASSWORD', 'subhash'),
        'HOST': os.environ.get('CLEAR_DB_HOST', 'localhost'),
        'PORT': os.environ.get('CLEAR_DB_PORT', '5432'),
        'OPTIONS': {
            # Resolve unqualified table names against the `clear` schema.
            'options': '-c search_path=clear,public',
        },
    },
}

DATABASE_ROUTERS = ['line_inspection.db_router.ClearDbRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Uploads: an inspection can carry up to 12 photos at ~2-4 MB each, so allow
# generous multipart bodies but still cap them against abuse/mistakes.
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024   # 200 MB request body
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024     # >5 MB files spool to disk
DATA_UPLOAD_MAX_NUMBER_FILES = 20

REST_FRAMEWORK = {
    # JSON-only API: the browsable HTML renderer leaks schema/config detail
    # and is unnecessary for a mobile-app backend.
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
}

# Structured console logging (picked up by any process manager / journald /
# container runtime). App code logs under the "inspections" logger.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {'level': 'WARNING'},
        'inspections': {'level': 'INFO'},
    },
}

# Hardening that only makes sense behind HTTPS — activates automatically
# when DEBUG is turned off in production.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True