# Generated by Django 5.2 on 2026-07-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_line_id', models.IntegerField()),
                ('tower_location', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('defect', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='inspections/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
