# Generated by Django 5.2 on 2026-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='component',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='defect',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
