# Generated by Django 5.2.15 on 2026-07-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspection_options_inspection_captured_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='image',
            field=models.ImageField(upload_to='inspections/'),
        ),
    ]
