# Generated by Django 5.2.15 on 2026-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_remove_inspection_image_inspectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['transmission_line_id', 'tower_location'], name='insp_line_tower_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['-created_at'], name='insp_created_idx'),
        ),
    ]
