# Generated by Django 5.2.15 on 2026-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspection_client_id_inspection_insp_line_tower_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/thumbs/'),
        ),
    ]
